--- 

- hosts: openstack
  gather_facts: yes
  become: yes
  vars_files:
    - variables.yaml
  tasks:
    - import_role:
        name: compute

- hosts: control
  gather_facts: yes
  become: yes
  vars_files:
    - variables.yaml
  tasks:
    - import_role:
        name: packstack
