--- 

- hosts: k8s
  gather_facts: yes
  become: yes
  vars_files:
    - variables.yaml
  tasks:
    - import_role:
        name: worker
    - import_role:
        name: docker
    - import_role:
        name: kubeadm
