- name: check if helper is already up
  wait_for:
    port: 22
    host: "{{ hostvars['ocp-helper']['ansible_host'] }}"
    delay: 5
    timeout: 10
    msg: "Timeout waiting for 22 to respond"
  register: port_check
  ignore_errors: yes
 
- set_fact: 
    helper_running: "{{ True if port_check.failed == False else False }}"

- name: create helper vagrant dir
  when: port_check.failed == true
  file:
    path: /opt/ocp-helper
    state: directory
    mode: '0777'

- name: copy helper vagrant file
  when: port_check.failed == true
  template: 
    src: helper.vagrant
    dest: /opt/ocp-helper/Vagrantfile
    mode: 0777

- name: create helper VM with vagrant - this may take some time
  when: port_check.failed == true
  command: vagrant up
  args:
    chdir: /opt/ocp-helper

- name: Wait for port 22
  when: port_check.failed == true
  wait_for:
    port: 22
    host: "{{ hostvars['ocp-helper']['ansible_host'] }}"
    delay: 10
