# create k8s vms
- name: check if master node is up
  delegate_to: basehost
  when: kubernetes_install == true
  wait_for:
    port: 22
    host: "{{ hostvars['master1']['ansible_host'] }}"
    delay: 5
    timeout: 10
    msg: "Timeout waiting for 22 to respond"
  register: port_check
  ignore_errors: yes
 
- set_fact: 
    kubernetes_running: "{{ True if port_check.failed == False else False }}"
  when: kubernetes_install == true

- debug: 
    var: kubernetes_running

- name: create k8s vagrant dir
  when: kubernetes_install == true and port_check.failed == true
  file:
    path: /opt/k8s
    state: directory
    mode: '0777'

- name: copy k8s vagrant file
  when: kubernetes_install == true and port_check.failed == true
  template: 
    src: k8s.vagrant
    dest: /opt/k8s/Vagrantfile
    mode: 0777

- name: create k8s VMs with vagrant - this may take some time
  when: kubernetes_install == true and port_check.failed == true
  command: vagrant up
  args:
    chdir: /opt/k8s

# test that ssh is running on master node
- name: Wait for port 22 to become open
  when: kubernetes_install == true and port_check.failed == true
  delegate_to: basehost
  wait_for:
    port: 22
    host: "{{ hostvars[item]['ansible_host'] }}"
    delay: 10
  with_items: "{{ groups['k8s'] }}"

# install openstack vms
- name: check if control node is up
  delegate_to: basehost
  when: openstack_install == true
  wait_for:
    port: 22
    host: "{{ hostvars['controlnode']['ansible_host'] }}"
    delay: 5
    timeout: 10
    msg: "Timeout waiting for 22 to respond"
  register: port_check
  ignore_errors: yes

- set_fact: 
    openstack_running: "{{ true if port_check.failed == false else false }}"
  when: openstack_install == true 

- name: create openstack vagrant dir
  when: openstack_install == true and port_check.failed == true
  file:
    path: /opt/openstack
    state: directory
    mode: '0777'

- name: copy openstack vagrant file
  when: openstack_install == true and port_check.failed == true
  template: 
    src: openstack.vagrant
    dest: /opt/openstack/Vagrantfile
    mode: 0777

- name: create openstack VMs with vagrant - this may take some time
  when: openstack_install == true and port_check.failed == true
  command: vagrant up
  args:
    chdir: /opt/openstack

# test that ssh is running on control node
- name: Wait for port 22 to become open
  when: openstack_install == true and port_check.failed == true
  delegate_to: basehost
  wait_for:
    port: 22
    host: "{{ hostvars[item]['ansible_host'] }}"
    delay: 10
  with_items: "{{ groups['openstack'] }}"

# install AIO vm
- name: check if AIO node is up
  delegate_to: basehost
  when: AIO_VM == true
  wait_for:
    port: 22
    host: "{{ hostvars['lm']['ansible_host'] }}"
    delay: 5
    timeout: 10
    msg: "Timeout waiting for 22 to respond"
  register: port_check
  ignore_errors: yes

- name: create lm vagrant dir
  when: AIO_VM == true and port_check.failed == true
  file:
    path: /opt/lm
    state: directory
    mode: '0777'

- name: copy lm vagrant file
  when: AIO_VM == true and port_check.failed == true
  template: 
    src: lm.vagrant
    dest: /opt/lm/Vagrantfile
    mode: 0777

- name: create lm VM with vagrant - this may take some time
  when: AIO_VM == true and port_check.failed == true
  command: vagrant up
  args:
    chdir: /opt/lm

# test that ssh is running on lm node
- name: Wait for port 22 to become open
  when: AIO_VM == true and port_check.failed == true
  delegate_to: basehost
  wait_for:
    port: 22
    host: "{{ hostvars['lm']['ansible_host'] }}"
    delay: 10
