---
- name: Create web hosting directory for images and ignitions file
  file:
    path: "{{ item }}"
    state: directory
  tags:
      - configure_http_server
  with_items:
    - "{{ images_directory }}"
    - "{{ ignitions_directory }}"

- name: check if rhcos exists already 
  stat:
    path: "{{ images_directory }}/rhcos-4.2.18-x86_64-metal-bios.raw.gz"
  register: rhcos_result

- name: Downloading RHCOS 4.2.18 OS BIOS image
  get_url:
    url: "{{ rhcos_biosimg_url }}"
    dest: "{{ images_directory }}"
    timeout: 300
    validate_certs: false
  when: biossetup and rhcos_result.stat.exists == False 
  tags:
      - configure_http_server
      - download_rhcos_image

- name: Downloading RHCOS 4.2.18 OS UEFI image
  get_url:
    url: "{{ rhcos_biosimg_url }}"
    dest: "{{ images_directory }}"
    timeout: 300
    validate_certs: false
  when: uefisetup and rhcos_result.stat.exists == False 
  tags:
      - configure_http_server
      - download_rhcos_image

- name: Restoring SELinux fscontext
  shell: restorecon -RFv "{{ item }}"
  tags:
      - configure_http_server
  with_items:
    - "{{ images_directory }}"
    - "{{ ignitions_directory }}"

- name: Configure http to listen to 8080
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^Listen 80'
    line: 'Listen 8080'
  changed_when: True
  tags:
    - configure_http_server

- name: restart httpd
  service:
    name: httpd
    state: restarted
    enabled: yes
  tags:
    - configure_http_server