- name: install openvpn dependencies
  apt: name={{item}} state=present
  with_items:
     - openvpn
     - bridge-utils
     - easy-rsa

- name: copy openvpn server files
  become: yes
  copy:
    src: ../config/server/
    dest: /etc/openvpn/
    owner: root
    group: root
    mode: 0644

- name: copy openvpn server template
  become: yes
  template:
    src: ../config/server/server.conf
    dest: /etc/openvpn/server.conf
    owner: root
    group: root
    mode: 0644

- name: set ip forwarding
  become: yes
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_set: yes
    state: present
    reload: yes

- name: copy iptables script
  template:
    src: iptables.sh
    dest: /opt/iptables.sh

- name: apply forwarding rules
  become: yes
  script: /opt/iptables.sh  >> /opt/iptables.out

- name: start service openvpn
  become: yes
  service:
    name: openvpn@server
    state: started

- name: copy openvpn client 
  become: yes
  template:
    src: ../config/client/client-template.ovpn
    dest: client.ovpn
