- name: install unofficial centos openstack release
  yum:
    name:
      - centos-release-openstack-stein
    state: present
    update_cache: yes
  when: openstack_offical_redhat == false

- name: install packstack
  yum:
    name:
      - openstack-packstack
    state: present
    update_cache: yes

- name: copy answer to control node
  template:
    src: answer.txt
    dest: /opt/answer.txt
    mode: 0644

- name: run packstack
  command: packstack --answer-file=/opt/answer.txt

- name: Ensuring local directory to hold the os-client-config file
  file:
    path: /etc/openstack
    state: directory
    owner: root
    group: root

- name: copy clouds.yaml
  template:
    src: clouds.yaml
    dest: /etc/openstack/clouds.yaml
    owner: root
    group: root
    mode: 0700