####################################################################
# Install docker and add insecure registries
####################################################################

- name: Update apt cache
  raw: apt-get -y update

- name: Install base dependencies
  apt: 
    name: 
      - python
      - python-pip
      - python-apt
    state: present 
  become: yes

- name: Install Docker 
  block:
    - name: Install base dependencies
      apt: 
        name: ['apt-transport-https','ca-certificates','curl','software-properties-common'] 
        state: present

    - name: Add Docker GPG key
      apt_key: 
        url: https://download.docker.com/linux/ubuntu/gpg
        
    - name: Determine Docker APT repository
      shell: echo "deb https://download.docker.com/linux/$(. /etc/os-release; echo $ID) $(lsb_release -cs) stable"
      register: docker_apt_repository_output

    - name: Add Docker APT repository
      apt_repository:
        repo: "{{ docker_apt_repository_output.stdout }}"
        state: present
        update_cache: yes

    - name: Install docker-ce package
      apt: 
        name: ["docker-ce={{ docker_version }}"]
        state: present 
        force: yes
      become: yes

- name: Configure Docker insecure registries
  import_tasks: add-insecure-registries.yml
  when: (docker_insecure_registries | default([]) | length>0)

- name: Install Docker Compose
  pip: 
    name: docker-compose=={{ docker_compose_version }}
    state: present

