- name: stop firewalld
  systemd:
    name: firewalld
    state: stopped
    enabled: no

- name: stop NetworkManager
  systemd:
    name: NetworkManager
    state: stopped
    enabled: no

- name: start network
  systemd:
    name: network
    state: started
    enabled: yes

- name: install kvm
  yum:
    name:
      - qemu-kvm
      - libvirt 
      - libvirt-python 
      - libvirt-client 
      - libguestfs-tools
      - virt-install 
    state: present
  when: inventory_hostname in groups.compute

- name: start libvirt service
  systemd:
    name: libvirtd
    state: started
    enabled: yes
  when: inventory_hostname in groups.compute

- name: split ip address
  set_fact:
    iplist: "{{ hostvars[inventory_hostname]['ansible_host'].split('.') }}"

- name: set bridge address
  command: "ifconfig eth2 10.100.0.{{ iplist | last }}"

- name: add control node(s)
  lineinfile:
    path: /etc/hosts
    line: "{{ hostvars[item]['ansible_host'] }} {{ item }}"
    owner: root
    group: root
    mode: 0644
  loop: "{{ groups['control'] }}"

- name: add network node(s)
  lineinfile:
    path: /etc/hosts
    line: "{{ hostvars[item]['ansible_host'] }} {{ item }}"
    owner: root
    group: root
    mode: 0644
  loop: "{{ groups['network'] }}"
  loop_control:
    index_var: idx

- name: add compute node(s) 
  lineinfile:
    path: /etc/hosts
    line: "{{ hostvars[item]['ansible_host'] }} {{ item }}"
    owner: root
    group: root
    mode: 0644
  loop: "{{ groups['compute'] }}"
  loop_control:
    index_var: idx
