- name: create provider bond0
  template:
    src: ifcfg-bond0
    dest: /etc/sysconfig/network-scripts/
    mode: 0777

- name: configure eth3 provider NIC
  template:
    src: ifcfg-eth3
    dest: /etc/sysconfig/network-scripts/
    mode: 0777

- name: configure eth4 provider NIC
  template:
    src: ifcfg-eth4
    dest: /etc/sysconfig/network-scripts/
    mode: 0777

- name: restart networking
  systemd:
    state: restarted
    daemon_reload: yes
    name: network.service

- sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_set: yes

- sysctl:
    name: net.ipv4.conf.all.rp_filter
    value: 0
    sysctl_set: yes
