apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: mgmt
spec:
  config: '{
            "name": "mgmt",
            "type": "bridge",
            "bridge": "br-mgmt",
            "isDefaultGateway": true,
            "forceAddress": false,
            "ipMasq": true,
            "hairpinMode": true,
            "ipam": {
              "type": "host-local",
              "subnet": "10.0.30.0/24",
              "rangeStart": "10.0.30.55",
              "rangeEnd": "10.0.30.100"
            }
        }'