--- 

- hosts: basehost
  gather_facts: no
  become: yes
  tasks:
    - import_role:
        name: create-nodes

- hosts: k8s
  gather_facts: yes
  become: yes
  tasks:
    - import_role:
        name: setup-workers
      when: hostvars['basehost']['kubernetes_running'] == false
    - import_role:
        name: setup-docker
      when: hostvars['basehost']['kubernetes_running'] == false
    - import_role:
        name: configure-kubeadm
      when: hostvars['basehost']['kubernetes_running'] == false
