---
- name: Clean up previous working directory
  file:
    path: /opt/ocp4/
    state: absent
  tags: 
    - configure_ignitions_file
  
- name: Ensure working directory exists
  file:
    path: /opt/ocp4
    state: directory
  tags: 
    - configure_ignitions_file

- name: Prepare ignition files
  template:
    src: install-config.yaml.j2
    dest: /opt/ocp4/install-config.yaml
  tags: 
    - configure_ignitions_file

- name: Prepare ignition files
  template:
    src: install-config.yaml.j2
    dest: /opt/ocp4/install-config-base.yaml
  tags:
    - configure_ignitions_file

- name: Execute openshift installer file
  shell: /usr/bin/openshift-install create ignition-configs --dir=/opt/ocp4
  tags: 
    - configure_ignitions_file

- name: Ensure web hosting directory exists
  file:
    path: /var/www/html/
    state: directory
    owner: apache
    group: root
  tags: 
    - configure_ignitions_file
 
- name: Copy ign file to http hosted folder
  shell: cp -rvf /opt/ocp4/*.ign /var/www/html/
  tags: 
    - configure_ignitions_file

- name: Restore SELinux fcontext /var/www/html
  command: restorecon -RFv /var/www/html
  tags: 
    - configure_ignitions_file
