- name: add master node
  lineinfile:
    path: /etc/hosts
    line: "{{ hostvars[item]['ansible_host'] }} {{ item }}"
    owner: root
    group: root
    mode: 0644
  loop: "{{ groups['master'] }}"
  loop_control:
    index_var: idx

- name: add worker node(s) 
  lineinfile:
    path: /etc/hosts
    line: "{{ hostvars[item]['ansible_host'] }} {{ item }}"
    owner: root
    group: root
    mode: 0644
  loop: "{{ groups['workers'] }}"
  loop_control:
    index_var: idx

