--- 

- hosts: basehost
  gather_facts: yes
  become: yes
  tasks:
    - import_role:
        name: create-compute

- hosts: openstack
  gather_facts: yes
  become: yes
  tasks:
    - import_role:
        name: setup-compute
      when: hostvars['basehost']['kubernetes_running'] == false

- hosts: ostack_control
  gather_facts: yes
  become: yes
  tasks:
    - import_role:
        name: run-packstack
      when: hostvars['basehost']['kubernetes_running'] == false
