--- 

- hosts: basehost
  gather_facts: yes
  become: yes
  tasks:
    - import_role:
        name: create-compute

- hosts: openstack
  gather_facts: yes
  become: yes
  tasks:
    - import_role:
        name: setup-compute

- hosts: control
  gather_facts: yes
  become: yes
  tasks:
    - import_role:
        name: run-packstack
