clouds:
  openstack:
    auth:
      auth_url: http://{{ hostvars['oscontrol']['ansible_host'] }}/v3
      username: "admin"
      password: "password"
      project_name: "admin"
      user_domain_name: "Default"
      project_domain_name: "Default"
    identity_api_version: 3
