host_id: "{{ ansible_hostname }}"
analyzers: 
  - "{{ hostvars['basehost']['ansible_host'] }}:8082"
agent:
  listen: 0.0.0.0:8081
  topology:
    probes:
      - netns
      - netlink
      - docker
      - ovsdb
      - neutron
      - libvirt
  flow:
    probes:
      - ovssflow