- name: create br-tun
  openvswitch_bridge:
    bridge: br-tun
    state: present

- name: create br-ex
  openvswitch_bridge:
    bridge: br-ex
    state: present

- name: assign br-ex ip address
  command: "ifconfig br-ex {{ openstack_bridge_ip }}"