- name: If needed, install Python
  raw: apt-get update && apt-get -y install python python-pip

- setup:

- name: Install base dependencies
  action: >
    {{ ansible_pkg_mgr }} name={{ item }} state=present update_cache=yes
  with_items:
      - apt-transport-https
      - ca-certificates
      - curl
      - build-essential
      - git
      - software-properties-common
      - openvswitch-switch
      - htop
      - bridge-utils
      - python
      - python-pip
      - net-tools
      - qemu-kvm
      - virt-manager
      - virtinst

- name: start libvirt service
  systemd:
    name: libvirtd
    state: started
    enabled: yes

- name: Install vncserver
  action: >
    {{ ansible_pkg_mgr }} name={{ item }} state=present update_cache=yes
  with_items:
      - xfce4 
      - xfce4-goodies
      - tightvncserver
      - firefox

# - name: set vnc password
#   command: "echo accantodemo | vncpasswd -f > {{ '~' + ansible_user | expanduser }}/.vnc/passwd"

# - name: Run vnc server for first time
#   expect:
#     command: vncserver
#     responses:
#       (.*)Password(.*): accantodemo
#       (.*)Verify(.*): accantodemo

# - name: kill vncserver
#   command: vncserver -kill :2

- name: Ensure .vnc directory exists
  file:
    path: "{{ '~' + ansible_user | expanduser }}/.vnc/xstartup"
    state: directory
    mode: '0777'    

- name: Update xstart file
  template:
    src: xstartup
    dest: "{{ '~' + ansible_user | expanduser }}/.vnc/xstartup"

# - name: Run vnc server
#   command: vncserver

- name: Install vagrant
  apt:
    name: vagrant

- name: Install vagrant dependencies for libvirt plugin
  action: >
    {{ ansible_pkg_mgr }} name={{ item }} state=present update_cache=yes
  with_items:
      - qemu 
      - libvirt-bin 
      - ebtables 
      - dnsmasq-base
      - libxslt-dev 
      - libxml2-dev 
      - libvirt-dev 
      - zlib1g-dev 
      - ruby-dev

- name: Install vagrant libvirt plugin
  command: vagrant plugin install vagrant-libvirt

- name: remove any domain search in resolv.conf
  shell: "sed -e 's/^search/#search/' -i /etc/resolv.conf"
